export const FEATCH_WEATHER_PENDING = "FEATCH_WEATHER_PENDING";

export const FEATCH_CURRENT_SUCCESS = "FEATCH_CURRENT_SUCCESS";
export const FEATCH_FORCAST_SUCCESS = "FEATCH_FORCAST_SUCCESS";

export const FEATCH_WEATHER_ERROR = "FEATCH_WEATHER_ERROR";

export const SET_CITY = "SET_CITY";
